/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc20VotesSol from "./ERC20Votes.sol";
export type { erc20VotesSol };
import type * as tokenSol from "./Token.sol";
export type { tokenSol };
import type * as tokenizedBallotSol from "./TokenizedBallot.sol";
export type { tokenizedBallotSol };
export type { Lottery } from "./Lottery";
