/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as erc20VotesSol from "./ERC20Votes.sol";
export * as tokenSol from "./Token.sol";
export * as tokenizedBallotSol from "./TokenizedBallot.sol";
export { Lottery__factory } from "./Lottery__factory";
